### ISSUE TITLE
OpenC2X does not build

### ISSUE THREAD

**Issue by ehamzic1** [florianklingler/OpenC2X-embedded#2]
When trying to build OpenC2X-embedded (integrated with OpenWrt) from this Github repository, I have encountered a build error that results from conflicting function names. There are two functions named copy_file_range - one is in the create_inode.c file and the other one in the unistd.h header that the mentioned file includes. What I would like to know is if someone else has encountered this previously and if there is some known fix or an elegant way to handle this issue that you might have come up with.

The running setups I have tried this on are Linux Mint 19 and Ubuntu 18.04.2 run as a virtual machine (fully installed version)
The build error is very simple to reproduce, we do as follows:
1) Clone this Github repository
2) Run the commands as listed in the readme.md file
3) You might going to have to install a few dependencies (I had to install three of them) - they are going to be listed in the terminal when you run the second command from the readme file above (./scripts/feeds install -a). I have listed these, as well as how to install them in an attached file named Dependencies.
[Dependencies.pdf](https://github.com/florianklingler/OpenC2X-embedded/files/3362596/Dependencies.pdf)

**Comment by florianklingler** [comment]
see here: https://github.com/openwrt/openwrt/pull/781
